package ui.main;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import dao.Employee_DAO;
import database.ConnectDB;
import entity.Employee;
import ui.table.TableCustom;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;

public class EmployeeSearch extends javax.swing.JPanel {

    public EmployeeSearch() {
        initComponents();
        ConnectDB.getInstance().connect();
        employee_dao = new Employee_DAO();
        JTableHeader theader = tableEmployee.getTableHeader();
        theader.setFont(new java.awt.Font("Segoe UI", 0, 18));

        TableCustom.apply(scrollPane_tableEmployee, TableCustom.TableType.MULTI_LINE);
        tableEmployee.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        if (tableEmployee.getColumnModel().getColumnCount() > 0) {
            tableEmployee.getColumnModel().getColumn(0).setPreferredWidth(130);
            tableEmployee.getColumnModel().getColumn(1).setPreferredWidth(240);
            tableEmployee.getColumnModel().getColumn(2).setPreferredWidth(130);
            tableEmployee.getColumnModel().getColumn(3).setPreferredWidth(120);
            tableEmployee.getColumnModel().getColumn(4).setPreferredWidth(89);
            tableEmployee.getColumnModel().getColumn(5).setPreferredWidth(95);
            tableEmployee.getColumnModel().getColumn(6).setPreferredWidth(279);
            tableEmployee.getColumnModel().getColumn(7).setPreferredWidth(319);
            tableEmployee.getColumnModel().getColumn(8).setPreferredWidth(108);
        }
        txtEmplID.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {

            }

            @Override
            public void keyPressed(KeyEvent e) {

            }

            @Override
            public void keyReleased(KeyEvent e) {
                searchEmployee();
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCenter = new javax.swing.JPanel();
        scrollPane_tableEmployee = new javax.swing.JScrollPane();
        tableEmployee = new javax.swing.JTable();
        lbTitlePane = new javax.swing.JLabel();
        lbTitleTable = new javax.swing.JLabel();
        txtEmplID = new ui.textfield.TextField();
        btnSearch = new ui.button.Button();

        setPreferredSize(new java.awt.Dimension(1620, 1000));
        setLayout(new java.awt.BorderLayout());

        pCenter.setBackground(new java.awt.Color(242, 249, 255));
        pCenter.setPreferredSize(new java.awt.Dimension(1600, 1000));

        scrollPane_tableEmployee.setBackground(new java.awt.Color(221, 221, 221));
        scrollPane_tableEmployee.setBorder(null);

        tableEmployee.setBackground(new java.awt.Color(242, 249, 255));
        tableEmployee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tableEmployee.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String[]{
                        "Mã nhân viên", "Tên nhân viên", "Số điện thoại", "Ngày sinh", "Giới tính", "Trình độ", "Email", "Địa chỉ","Trạng thái"
                }
        ));
        tableEmployee.setGridColor(new java.awt.Color(218, 247, 249));
        scrollPane_tableEmployee.setViewportView(tableEmployee);

        lbTitlePane.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbTitlePane.setForeground(new java.awt.Color(102, 204, 255));
        lbTitlePane.setText("THÔNG TIN NHÂN VIÊN");

        lbTitleTable.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTitleTable.setForeground(new java.awt.Color(102, 204, 255));
        lbTitleTable.setText("DANH SÁCH NHÂN VIÊN");

        txtEmplID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmplID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmplIDActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(102, 204, 255));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Tìm kiếm");
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout pCenterLayout = new javax.swing.GroupLayout(pCenter);
        pCenter.setLayout(pCenterLayout);
        pCenterLayout.setHorizontalGroup(
                pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCenterLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCenterLayout.createSequentialGroup()
                                                .addComponent(lbTitlePane)
                                                .addGap(590, 590, 590))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCenterLayout.createSequentialGroup()
                                                .addComponent(lbTitleTable)
                                                .addGap(645, 645, 645))))
                        .addGroup(pCenterLayout.createSequentialGroup()
                                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pCenterLayout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addComponent(scrollPane_tableEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 1510, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pCenterLayout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(txtEmplID, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(71, 71, 71)
                                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(54, Short.MAX_VALUE))
        );
        pCenterLayout.setVerticalGroup(
                pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pCenterLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lbTitlePane, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(pCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtEmplID, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                        .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(lbTitleTable)
                                .addGap(45, 45, 45)
                                .addComponent(scrollPane_tableEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79))
        );

        add(pCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmplIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmplIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmplIDActionPerformed

    private void searchEmployee(){
        DefaultTableModel model = (DefaultTableModel) tableEmployee.getModel();
        model.setRowCount(0); // Xóa các dòng hiện tại
        String criteria = txtEmplID.getText().trim();

        // Gọi phương thức tìm kiếm từ Customer_DAO
        ArrayList<Employee> searchResults = employee_dao.getEmployeeByCriterious(criteria);
        if(searchResults.isEmpty()){
            model.addRow(new Object[] {"...","...","...","...","...","...","...","...","..."});
            // Tùy chọn: Căn chỉnh cột đầu tiên cho thông báo
        }
        for (Employee employee : searchResults) {
            model.addRow(new Object[]{
                    employee.getEmployeeID(),
                    employee.getEmployeeName(),
                    employee.getPhoneNumber(),
                    employee.getBirthDate(),
                    employee.isGender()?"Nữ":"Nam",
                    employee.getDegree(),
                    employee.getEmail(),
                    employee.getAddress(),
                    employee.isStatus()?"Đang làm":"Nghỉ làm"
            });
        }
        if(txtEmplID.getText().isEmpty() ){
            model.setRowCount(0); // Xóa các dòng hiện tại
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.button.Button btnSearch;
    private javax.swing.JLabel lbTitlePane;
    private javax.swing.JLabel lbTitleTable;
    private javax.swing.JPanel pCenter;
    private javax.swing.JScrollPane scrollPane_tableEmployee;
    private javax.swing.JTable tableEmployee;
    private ui.textfield.TextField txtEmplID;
    private Employee_DAO employee_dao;
    // End of variables declaration//GEN-END:variables

}
